version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - /home/drigolx/Dev/db:/var/lib/postgresql/data
    networks:
      - dev-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - dev-network
    depends_on:
      - postgres

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8001:8001'
    volumes:
      - /home/drigolx/Dev/redisdb:/db
    depends_on:
      - redis
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
# on the GNU/Linux, you need to up container with this command bellow
# sh createdir.sh && docker-compose up -d
