version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password of postgresql"
    ports:
      - "5432:5432"
    volumes:
      - /home/drigolx/Dev/db:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
